# ~/.config/sheldon/plugins.toml

[plugins.zsh-defer]
github = "romkatv/zsh-defer"

[templates]
defer = "{% for file in files %}zsh-defer source \"{{ file }}\"\n{% endfor %}"
PATH = 'export PATH="$PATH:{{ dir }}"'

[plugins.starship]
inline = 'eval "$(starship init zsh)"'

[plugins.zsh-syntax-highlighting]
github = "zsh-users/zsh-syntax-highlighting"

[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"
use = ["{{ name }}.zsh"]

[plugins.z-lua]
github = "skywind3000/z.lua"

[plugins.zsh-emacs]
github = "Flinner/zsh-emacs"

[plugins.zsh-sudo]
github = "hcgraf/zsh-sudo"

[plugins.ripz]
github = "jedahan/ripz"

[plugins.zsh-rust]
github = "cowboyd/zsh-rust"

[plugins.alacritty-shell]
github = "casonadams/alacritty-shell"

[plugins.zsh-histoy-substring-search]
github = "zsh-users/zsh-history-substring-search"

