format = """
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$fill\
$cmd_duration\
$time\
$line_break\
$character"""

[directory]
style = "blue"

[character]
success_symbol = "[λ](purple)"
error_symbol = "[λ](red)"

[git_branch]
format = "[$symbol$branch]($style)"
style = "bright-black"

[git_status]
format = "[[(*$conflicted$untracked$modified$staged$renamed$deleted)](218)[($stashed)](184)($ahead_behind)]($style)"
style = "cyan"
conflicted = "​"
untracked = "​"
modified = "​"
staged = "​"
renamed = "​"
deleted = "​"
stashed = "≡"

[git_state]
format = "[($state($progress_current/$progress_total))]($style)"
style = "bright-black"

[cmd_duration]
format = "[$duration]($style) "
style = "yellow"

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
format = "[$time]($style) "
style = "gray"

